CREATE TABLE IF NOT EXISTS users(
	uid SERIAL PRIMARY KEY,
	first_name TEXT NOT NULL,
	last_name TEXT NOT NULL,
	email TEXT UNIQUE NOT NULL,
	password TEXT NOT NULL,
	profile_pic TEXT,
	bio TEXT
);
CREATE TABLE IF NOT EXISTS recipes(
	rid SERIAL PRIMARY KEY,
	title VARCHAR(50) NOT NULL,
	description TEXT NOT NULL,
	rdate DATE NOT NULL DEFAULT CURRENT_DATE,
	rtime TIME WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIME AT TIME ZONE 'AEST'),
	cuisine TEXT,
	mealtype TEXT,
	video TEXT,
    image TEXT,
	course BOOLEAN NOT NULL DEFAULT 'f',
    prep_time INTEGER NOT NULL,
    cook_time INTEGER NOT NULL,
    method TEXT NOT NULL,
	uid BIGINT REFERENCES users ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS steps(
	sid SERIAL PRIMARY KEY,
	rid BIGINT REFERENCES recipes ON DELETE CASCADE,
	instructions TEXT NOT NULL,
	image TEXT,
	timer TEXT,
	PRIMARY KEY (rid, step_number)
);

CREATE TABLE IF NOT EXISTS ingredients(
	iid SERIAL PRIMARY KEY,
	name TEXT UNIQUE NOT NULL
);

CREATE TABLE IF NOT EXISTS quantities(
	qid SERIAL PRIMARY KEY,
	rid BIGINT REFERENCES recipes ON DELETE CASCADE,
	iid BIGINT REFERENCES ingredients ON DELETE CASCADE,
	technique TEXT,
	quantity TEXT NOT NULL,
	unit TEXT NOT NULL
);

CREATE TABLE IF NOT EXISTS likes(
	uid BIGINT REFERENCES users ON DELETE CASCADE,
	rid BIGINT REFERENCES recipes ON DELETE CASCADE,
	PRIMARY KEY (uid, rid)
);

CREATE TABLE IF NOT EXISTS comments(
	cid SERIAL PRIMARY KEY,
	uid BIGINT REFERENCES users ON DELETE CASCADE,
	rid BIGINT REFERENCES recipes ON DELETE CASCADE,
	comment TEXT NOT NULL,
	cdate DATE NOT NULL DEFAULT CURRENT_DATE,
	ctime TIME WITH TIME ZONE NOT NULL DEFAULT (CURRENT_TIME AT TIME ZONE 'AEST')
);

CREATE TABLE IF NOT EXISTS flagged_comments(
	cid INTEGER REFERENCES comments,
    uid INTEGER REFERENCES user,
    PRIMARY KEY (cid, uid)
);

CREATE TABLE IF NOT EXISTS subscribers(
	subid BIGINT REFERENCES users ON DELETE CASCADE,
	conid BIGINT REFERENCES users ON DELETE CASCADE,
	PRIMARY KEY(subid, conid)
);

CREATE TABLE IF NOT EXISTS payments(
	pid SERIAL PRIMARY KEY,
	uid BIGINT REFERENCES users ON DELETE CASCADE,
	conid BIGINT REFERENCES users ON DELETE CASCADE,
	payment TEXT NOT NULL
);

